# Generated by Django 4.2.20 on 2025-04-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='product_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
