# Generated by Django 4.2.20 on 2025-04-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='toolcategory',
            options={'verbose_name_plural': 'Tool Categories'},
        ),
        migrations.AlterModelOptions(
            name='yarncategory',
            options={'verbose_name_plural': 'Yarn Categories'},
        ),
    ]
